name: Che kavo

on:
  workflow_dispatch:

jobs:
  chekavo-runner-1:
    name: Runner
    runs-on: ubuntu-latest
    env:
      SOME_SECRET: hijack
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
        cd ./actions/pwn-test
        npm ci
    - name: Yoyoyo
      uses: ./actions/pwn-test
      with:
        who-to-greet: "Ninja"